from enum import Enum

class UserRole(str, Enum):
    ADMIN = "ADMIN"
    SETTER = "SETTER"
    REVIEWER = "REVIEWER"
    COMPILER = "COMPILER"
    KEYHOLDER = "KEYHOLDER"
    CENTRE = "CENTRE"

class QuestionStatus(str, Enum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    USED = "USED"

class ReviewStatus(str, Enum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"

class ExamStatus(str, Enum):
    DRAFT = "DRAFT"
    COMPILING = "COMPILING"
    COMPILED = "COMPILED"
    ENCRYPTED = "ENCRYPTED"
    KEYS_SPLIT = "KEYS_SPLIT"
    RELEASED = "RELEASED"
    COMPLETED = "COMPLETED"

class PaperStatus(str, Enum):
    COMPILED = "COMPILED"
    ENCRYPTED = "ENCRYPTED"
    KEYS_DISTRIBUTED = "KEYS_DISTRIBUTED"
    RELEASED = "RELEASED"

class AuditAction(str, Enum):
    LOGIN = "LOGIN"
    FAILED_LOGIN = "FAILED_LOGIN"
    QUESTION_CREATE = "QUESTION_CREATE"
    QUESTION_EDIT = "QUESTION_EDIT"
    QUESTION_SUBMIT = "QUESTION_SUBMIT"
    QUESTION_REVIEW = "QUESTION_REVIEW"
    COMPILATION = "COMPILATION"
    ENCRYPTION = "ENCRYPTION"
    KEY_SPLIT = "KEY_SPLIT"
    KEY_SUBMIT = "KEY_SUBMIT"
    RELEASE_ATTEMPT = "RELEASE_ATTEMPT"
    RELEASE_SUCCESS = "RELEASE_SUCCESS"
    DOWNLOAD = "DOWNLOAD"
    DECRYPTION = "DECRYPTION"
    ROLE_CHANGE = "ROLE_CHANGE"
    LOCKDOWN = "LOCKDOWN"
